name: py311aiwatermark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - scipy=1.16.1
  - setuptools=78.1.1
  - wheel=0.45.1
  - tqdm=4.67.1
  - loguru=0.7.3
  - click=8.2.1
  - pillow=9.5.0
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio>=2.0.0
      - transformers==4.48.3
      - diffusers==0.27.2
      - accelerate==1.10.0
      - IOPaint==1.4.3
      - opencv-python-headless==4.11.0.86
      - PyQt6==6.9.1
      - huggingface-hub==0.24.6
      - safetensors==0.6.2
      - tokenizers==0.21.4
      - requests==2.32.4
      - Jinja2==3.1.6
      - packaging==25.0
      - psutil==7.0.0